services:
  - type: web
    runtime: static
    name: agenda-stance
    buildCommand: ""
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /tasks
        destination: https://stance-planner-api.onrender.com/tasks
      - type: rewrite
        source: /tasks/*
        destination: https://stance-planner-api.onrender.com/tasks/*
        